config/routes.rb
Rails.application.routes.draw do

  root 'figures#index'

  resources :figures, only: [:index, :new] do
    get :intersect, on: :collection
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  def index
  end

  def new
    render json: {
      html: render_to_string(
        partial: "figures/form_fields/#{params[:figure]}_fields",
        formats: [:html], layout: false
      )
    }
  end

  def intersect
    if params[:figures]
      intersection_service = IntersectionService.new(figures: params[:figures])
      @intersections = intersection_service.result
      render 'intersect'
    else
      flash[:danger] = 'Form contains errors'
      redirect_to figures_path
    end
  rescue FiguresIntersection::BaseFigure::ValidateError, FactoryException
    flash[:danger] = 'Form contains errors'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/figure_helper.rb
module FigureHelper
  def render_figure(figure)
    if figure.is_a?(FiguresIntersection::Point)
      render partial: 'figures/point', locals: { point: figure }
    elsif figure.is_a?(FiguresIntersection::Rectangle)
      render partial: 'figures/rectangle', locals: { rectangle: figure }
    elsif figure.is_a?(FiguresIntersection::Segment)
      render partial: 'figures/segment', locals: { segment: figure }
    elsif figure.is_a?(FiguresIntersection::StraightLine)
      render partial: 'figures/straight_line', locals: { straight_line: figure }
    elsif figure.is_a?(FiguresIntersection::VerticalLine)
      render partial: 'figures/vertical_line', locals: { vertical_line: figure }
    else
      render partial: 'figures/not_intersection'
    end
  end

  def coords_step
    0.01
  end
end

app/views/figures/_not_intersection.html.slim
.not-intersection
  |Not intersection

app/views/figures/_point.html.slim
.figure
  .label
    |Point
  = "x: #{point.x} y: #{point.y}"

app/views/figures/_rectangle.html.slim
.figure
  .label
    |Rectangle
  = "x: #{rectangle.x} y: #{rectangle.y} x1: #{rectangle.x1} y1: #{rectangle.y1}"

app/views/figures/_segment.html.slim
.figure
  .label
    |Segment
  = "x: #{segment.x} y: #{segment.y} x1: #{segment.x1} y1: #{segment.y1}"

app/views/figures/_straight_line.html.slim
.figure
  .label
    |Straight line
  = "k: #{straight_line.k} b: #{straight_line.b}"

app/views/figures/_vertical_line.html.slim
.figure
  .label
    |Vertical line
  = "a: #{vertical_line.a}"

app/views/figures/form_fields/_point_fields.html.slim
.figure-form
  .label
    |Point
  'x:
  = number_field_tag 'figures[points][x][]', nil, step: coords_step, required: true
  'y:
  = number_field_tag 'figures[points][y][]', nil, step: coords_step, required: true
  = render partial: 'figures/form_fields/remove_form'

app/views/figures/form_fields/_rectangle_fields.html.slim
.figure-form.js-rectangle-form
  .label
    |Rectangle
  'x:
  = number_field_tag 'figures[rectangles][x][]', nil, step: coords_step, required: true
  'y:
  = number_field_tag 'figures[rectangles][y][]', nil, step: coords_step, required: true
  'x1:
  = number_field_tag 'figures[rectangles][x1][]', nil, step: coords_step, required: true
  'y1:
  = number_field_tag 'figures[rectangles][y1][]', nil, step: coords_step, required: true
  = render partial: 'figures/form_fields/remove_form'

app/views/figures/form_fields/_remove_form.html.slim
span.js-remove-form
  i class="fa fa-times" aria-hidden="true"

app/views/figures/form_fields/_segment_fields.html.slim
.figure-form.js-segment-form
  .label
    |Segment
  'x:
  = number_field_tag 'figures[segments][x][]', nil, step: coords_step, required: true
  'y:
  = number_field_tag 'figures[segments][y][]', nil, step: coords_step, required: true
  'x1:
  = number_field_tag 'figures[segments][x1][]', nil, step: coords_step, required: true
  'y1:
  = number_field_tag 'figures[segments][y1][]', nil, step: coords_step, required: true
  = render partial: 'figures/form_fields/remove_form'

app/views/figures/form_fields/_straight_line_fields.html.slim
.figure-form
  .label
    |Straight line
  'k:
  = number_field_tag 'figures[straight_lines][k][]', nil, step: coords_step, required: true
  'b:
  = number_field_tag 'figures[straight_lines][b][]', nil, step: coords_step, required: true
  = render partial: 'figures/form_fields/remove_form'

app/views/figures/form_fields/_vertical_line_fields.html.slim
.figure-form
  .label
    |Vertical line
  'a:
  = number_field_tag 'figures[vertical_lines][a][]', nil, step: coords_step, required: true
  = render partial: 'figures/form_fields/remove_form'

app/views/figures/index.html.slim
.figures
  ul
    li
      = link_to 'Point', new_figure_path(figure: 'point'), class: 'js-add-figure'
    li
      = link_to 'Straight line', new_figure_path(figure: 'straight_line'), class: 'js-add-figure'
    li
      = link_to 'Vertical line', new_figure_path(figure: 'vertical_line'), class: 'js-add-figure'
    li
      = link_to 'Segment', new_figure_path(figure: 'segment'), class: 'js-add-figure'
    li
      = link_to 'Rectangle', new_figure_path(figure: 'rectangle'), class: 'js-add-figure'

.dashboard.js-dashboard
  = form_tag(intersect_figures_path, method: :get, class: 'js-compare-form') do
    ul.figures

    .button
      = submit_tag 'Find intersections'

app/views/figures/intersect.html.slim
.back
  = link_to 'Return to Back', root_path

.result
  - if @intersections.present?
    - @intersections.each do |intersection|
      .intersection-result
        .figure
          = render_figure(intersection.first_figure)
        .figure
          = render_figure(intersection.second_figure)
        .figure
          'Result:
          = render_figure(intersection.result)
  - else
    | Not intersections

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{ name.to_s == 'notice' ? 'success' : 'danger'}"
      = content_tag :div, id: "flash_#{name}" do
        = msg
        i class="fa fa-times js-close-message" aria-hidden="true"

app/views/layouts/application.html.slim
doctype html
html
  head
    title FiguresIntersectionApp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      .row
        .col-md-12
          .row
            = render partial: 'layouts/messages'
          .row
            = yield